Repository uc-cdis/gen3-helm, pull requests merged in 2025-10, with the labels that each got.

#406 Update portal-service.conf
  helm/gen3/Chart.yaml
  helm/gen3/README.md
  helm/revproxy/Chart.yaml
  helm/revproxy/README.md
  helm/revproxy/gen3.nginx.conf/gen3ff-as-root/portal-service.conf
Labels: TestPFBExport, TestGraphSubmitAndQuery, TestDiscoveryPage, TestDataUpload, TestGen3Client

#374 Add cronjob and update audit/values.yaml
  docs/audit_service_cron_deployment.md
  helm/audit/Chart.yaml
  helm/audit/README.md
  helm/audit/templates/audit-service-export-cron.yaml
  helm/audit/templates/audit-service-export-sa.yaml
  helm/audit/values.yaml
  helm/gen3/Chart.yaml
  helm/gen3/README.md
Labels: TestUserDataLibrary

#383 Feat/configure agg mds schedule
  helm/gen3/Chart.yaml
  helm/gen3/README.md
  helm/metadata/Chart.yaml
  helm/metadata/README.md
  helm/metadata/templates/agg-mds-sync.yaml
  helm/metadata/values.yaml
Labels: TestDiscoveryPage
