Repository uc-cdis/gen3-helm, pull requests merged in 2025-08, with the labels that each got.

#342 Add integration test workflow
  .github/workflows/integration_tests.yaml
Labels: TestDbgap, TestPFBExport, TestUserToken, TestGraphSubmitAndQuery

#362 Enable custom setting for PULL_FREQUENCY_SECONDS in audit service
  helm/audit/Chart.yaml
  helm/audit/README.md
  helm/audit/templates/secrets.yaml
  helm/audit/values.yaml
  helm/gen3/Chart.yaml
  helm/gen3/README.md
Labels: TestAuditService

#366 Add AGG_MDS_DEFAULT_DATA_DICT_FIELD to job
  helm/gen3/Chart.yaml
  helm/gen3/README.md
  helm/metadata/Chart.yaml
  helm/metadata/README.md
  helm/metadata/templates/agg-mds-sync.yaml
  helm/metadata/values.yaml
Labels: TestPFBExport
